[package]
name = "srp"
version = "0.4.1"
edition = "2018"
authors = ["RustCrypto Developers"]
license = "MIT OR Apache-2.0"
description = "Secure Remote Password (SRP) protocol implementation"
documentation = "https://docs.rs/srp"
repository = "https://github.com/RustCrypto/PAKEs"
keywords = ["crypto", "pake", "authentication"]
categories = ["cryptography", "authentication"]

[dependencies]
digest = "0.8"
lazy_static = "1.3.0"
num-traits = { version = "0.2.6", default-features = false }
# Currently the only `std` crate
num-bigint = "0.2.2"

[dev-dependencies]
rand = "0.6"
sha2 = "0.8"
sha-1 = "0.8"

[badges]
travis-ci = { repository = "RustCrypto/PAKEs" }
